### ISSUE TITLE
woff2 metadata?

### ISSUE THREAD

**Issue by campbellgraphics** [bramstein/homebrew-webfonttools#1]
Sorry if I'm missing something obvious, but the sfnt2woff tool allows you to add metadata by spec'ing an XML file. How do you go about doing something similar when making a woff2 font with the woff2 tool?

**Comment by bramstein** [comment]
You can store metadata in WOFF2 as well (http://www.w3.org/TR/WOFF2/#Metadata), but the tool doesn't yet support it.

**Comment by campbellgraphics** [comment]
Right, any advice on how to do that? I have tools that can add the metadata
to woff, but no tools that convert woff to woff2. Alternately, is there a
scriptable way to edit/add to woff2?

Thanks

Jason

On Saturday, January 24, 2015, Bram Stein notifications@github.com wrote:

> You can store metadata in WOFF2 as well (
> http://www.w3.org/TR/WOFF2/#Metadata), but the tool doesn't yet support
> it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bramstein/homebrew-webfonttools/issues/1#issuecomment-71303590
> .

## 

## 

Jason Campbell
jason@campbellgraphics.com
www.campbellgraphics.com
www.campbellcomics.com
Join me on Facebook: facebook.com/CampbellComics
http://facebook.com/CampbellComicsFollow me on Twitter:
twitter.com/campbellgraphic
781-799-0457

**Comment by bramstein** [comment]
I think your best bet is to open an issue on the woff2 repository (https://github.com/google/woff2) and ask for this feature. It doesn't look hard to implement, but I unfortunately don't have a use for it right now.

There is no tool that can convert from WOFF to WOFF2. This will always result in decompressing WOFF and recompressing as WOFF2. Metadata will most likely be lost in this process.

**Comment by davelab6** [comment]
I don't see why the XML metadata should be lost? :)

**Comment by bramstein** [comment]
@davelab6 The WOFF2 compressor doesn't support metadata yet. :)

**Comment by davelab6** [comment]
Oh I see, by 'most likely be lost' you mean 'will be lost until supported
by the compressor' :) Thanks!

**Comment by bramstein** [comment]
Yup, that's what I meant, sorry if that wasn't clear.
