### ISSUE TITLE
Cant install sfnt2woff-zopfli (SHA256 mismatch)

### ISSUE THREAD

**Issue by ditransler** [bramstein/homebrew-webfonttools#11]
Hello, Bram!

I tried to install sfnt2woff-zopfli but wasn't able to do so because of the following error: 
**SHA256 mismatch**.

```
Expected: 0da173a3f50ce4bb6b4817b3fcebb55a28c95546b852824f9cb16afefa8db45b
Actual: 135a211bdafdbd05a892ff627838f8822697f60154cfae371e08ad451207206f
```

(that was what brew printed out)

I also checked the tar.gz archive with this online tool ([defuse.ca](https://defuse.ca/checksums.htm)). It showed the same (actual) sha256.

Could you please check it out?

**Comment by bramstein** [comment]
Thanks for reporting this. Should hopefully be fixed now.

**Comment by ditransler** [comment]
Yes, thanks a lot! Now everything is fine.
