### ISSUE TITLE
sfnt2woff Formula Broken

### ISSUE THREAD

**Issue by DylanYoung** [bramstein/homebrew-webfonttools#14]
This appears to be because the site is down: http://people.mozilla.com/~jkew/woff/ 

Possible this is an issue on my end, so you should double check

**Comment by davelab6** [comment]
Site is definitely down

**Comment by bramstein** [comment]
If I remember correctly Jonathan Kew left Mozilla, so it looks like it won't be coming back either. I put my backup here: https://github.com/bramstein/sfnt2woff and temporarily updated the formula.

I'll reach out to Jonathan to see if he wants to host it himself somewhere.

**Comment by bramstein** [comment]
Looks like it's not coming back up, so I'll just keep pointing it to my fork.
