### ISSUE TITLE
Add AFDKO

### ISSUE THREAD

**Issue by bramstein** [bramstein/homebrew-webfonttools#15]
The AFDKO is a bit of a pain to install. Let's add it here so it just becomes `brew install afdko`.

**Comment by mashabow** [comment]
This is my attempt :)
https://github.com/mashabow/homebrew-mashabow/blob/ae17587fa92df34849bdf3239e90d2f9341a0d87/afdko.rb

**Comment by bramstein** [comment]
Nice! That looks good. Do you mind if I copy some of your formula (with proper credits/copyright of course)?

**Comment by mashabow** [comment]
OK, I created a PR.
